spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: canteen_db
    password: canteen_database123456
    url: jdbc:mysql://rm-bp1c16v5yyj31hvqabo.mysql.rds.aliyuncs.com/canteen?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    cache: false
server:
  servlet:
    context-path: /canteen
  port: 8080